import { defineConfig } from "tsdown";

export default defineConfig({
  entry: ["src/index.ts", "src/client.ts"],
  dts: true,
  // Every package is "type": "module", so plain .js files are ESM.
  fixedExtension: false,
  // Generated by the Graft Vite plugin in the user's app.
  deps: {
    neverBundle: [/^virtual:graft\//],
    // Bundled in, so the browser build doesn't have to resolve it from the user's app.
    alwaysBundle: ["devalue"],
  },
});
