// Modules generated by the Graft Vite plugin (packages/vite). They only exist
// inside a Vite build, so they stay external when this package is built.

declare module "virtual:graft/server" {
  /** The app's server entry: the default export of `app/server.ts`, or Graft's default. */
  const app: { fetch(request: Request): Response | Promise<Response> };
  export default app;
}
