import { defineConfig } from "tsdown";

export default defineConfig({
  // function.ts isn't imported by users: the adapter hands its built file to
  // the app's server build, which bundles it into the Vercel function.
  entry: ["src/index.ts", "src/function.ts"],
  dts: true,
  // Every package is "type": "module", so plain .js files are ESM.
  fixedExtension: false,
  // Generated by the Graft Vite plugin in the user's app.
  deps: {
    neverBundle: [/^virtual:graft\//],
  },
});
