import type { RouteNode } from "@phatjng/graft-router";

import type { RouteFile } from "./scan";

/**
 * Source for `virtual:graft/routes`.
 *
 * `routes` is the plain route tree. `modules` maps each route ID to a function
 * that imports its file. The imports are lazy so each page can become its own
 * chunk later, and only the matched route's code has to load.
 */
export function generateRoutesModule(tree: RouteNode, files: RouteFile[], appDir: string): string {
  const modules = files
    .map(
      ({ id, file }) =>
        `  ${JSON.stringify(id)}: () => import(${JSON.stringify(`${appDir}/${file}`)}),`,
    )
    .join("\n");

  return [
    `export const routes = ${JSON.stringify(tree)};`,
    `export const modules = {\n${modules}\n};`,
    "",
  ].join("\n");
}

/**
 * Source for `.graft/types/routes.d.ts`: the global `PageProps`,
 * `LayoutProps` and `LoaderProps` types, keyed by each route's URL pattern.
 *
 * `loaderData` is typed from each file's own `loader`, by importing the file's
 * type. devalue sends a Date as a Date (and so on), so no conversion is needed:
 * the data has exactly the type the loader returned.
 *
 * `appImportPath` is the path from the generated file to `app/`, e.g. `../../app`.
 */
export function generateRouteTypes(
  tree: RouteNode,
  files: RouteFile[],
  appImportPath: string,
): string {
  const fileById = new Map(files.map(({ id, file }) => [id, file]));
  const pages: string[] = [];
  const layouts: string[] = [];
  const params = new Map<string, string>();

  const entry = (path: string, id: string, own: string): string => {
    const file = fileById.get(id)!.replace(/\.[jt]sx?$/, "");
    return [
      `  ${JSON.stringify(path)}: {`,
      `    params: ${own};`,
      `    loaderData: LoaderDataOf<typeof import(${JSON.stringify(`${appImportPath}/${file}`)})>;`,
      `    actionData: ActionDataOf<typeof import(${JSON.stringify(`${appImportPath}/${file}`)})>;`,
      `  };`,
    ].join("\n");
  };

  const visit = (node: RouteNode, names: string[]): void => {
    const own = node.param === undefined ? names : [...names, node.param];
    const type = paramsType(own);

    if (node.page) pages.push(entry(node.path, node.page, type));
    if (node.layout) layouts.push(entry(node.path, node.layout, type));
    if (node.page || node.layout) params.set(node.path, type);
    node.children.forEach((child) => visit(child, own));
  };
  visit(tree, []);

  return `// Generated by Graft from the app/ folder. Do not edit.
/// <reference types="vite/client" />
import type { ReactNode } from "react";

/** The data a file's loader returns (without redirects), or undefined when it has none. */
type LoaderDataOf<Module> = Module extends { loader: (...args: any[]) => infer Result }
  ? Exclude<Awaited<Result>, Response>
  : undefined;

/** The data a file's action returns (without redirects). Undefined until the action has run. */
type ActionDataOf<Module> = Module extends { action: (...args: any[]) => infer Result }
  ? Exclude<Awaited<Result>, Response> | undefined
  : undefined;

interface GraftPages {
${pages.join("\n")}
}

interface GraftLayouts {
${layouts.join("\n")}
}

interface GraftParams {
${[...params].map(([path, type]) => `  ${JSON.stringify(path)}: ${type};`).join("\n")}
}

declare global {
  /** Props for the default export of a \`page\` file, e.g. \`PageProps<"/blog/[slug]">\`. */
  type PageProps<Route extends keyof GraftPages> = GraftPages[Route];

  /** Props for the default export of a \`layout\` file, e.g. \`LayoutProps<"/dashboard">\`. */
  type LayoutProps<Route extends keyof GraftLayouts> = GraftLayouts[Route] & {
    children: ReactNode;
  };

  /** What a \`loader\` receives, e.g. \`LoaderProps<"/blog/[slug]">\`. */
  type LoaderProps<Route extends keyof GraftParams> = {
    request: Request;
    params: GraftParams[Route];
  };

  /** What an \`action\` receives, e.g. \`ActionProps<"/blog/[slug]">\`. Read the form with \`await request.formData()\`. */
  type ActionProps<Route extends keyof GraftParams> = {
    request: Request;
    params: GraftParams[Route];
  };
}
`;
}

function paramsType(params: string[]): string {
  if (params.length === 0) return "{}";

  return `{ ${params.map((name) => `${name}: string`).join("; ")} }`;
}

/**
 * Source for `virtual:graft/server`, which becomes `dist/server/index.js`:
 * the app's `fetch` handler as the default export. Uses `app/server.*` when
 * it exists, otherwise hands every request to `handle()`.
 *
 * It also exports Vite's `base`, so `graft start` knows where to serve the
 * static files.
 */
export function generateServerEntry(
  appDir: string,
  userEntry: string | undefined,
  base: string,
): string {
  const lines = userEntry
    ? [`export { default } from ${JSON.stringify(`${appDir}/${userEntry}`)};`]
    : [
        `import { handle } from "@phatjng/graft/server";`,
        `export default { fetch: (request) => handle(request) };`,
      ];
  lines.push(`export const base = ${JSON.stringify(base)};`, "");

  return lines.join("\n");
}

/**
 * Source for `virtual:graft/client`: the first module the browser loads.
 * In dev it starts Vite's HMR client and React Fast Refresh first. Then it
 * runs `app/client.*` if it exists, or calls `hydrate()`.
 */
export function generateClientEntry(
  appDir: string,
  userEntry: string | undefined,
  dev: { viteClient: string } | undefined,
): string {
  const lines: string[] = [];
  if (dev) {
    lines.push(`import ${JSON.stringify(dev.viteClient)};`);
    // Must run before any component module, or Fast Refresh can't register them.
    lines.push(`import "@vitejs/plugin-react/preamble";`);
  }

  if (userEntry) {
    lines.push(`import ${JSON.stringify(`${appDir}/${userEntry}`)};`);
  } else {
    lines.push(`import { hydrate } from "@phatjng/graft/client";`, `hydrate();`);
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Source for `virtual:graft/assets` in dev. The dev server's module graph
 * lives in the plugin, outside the module runner that renders pages, so the
 * lookup goes through a global the plugin registers under `devKey`.
 */
export function generateDevAssetsModule(clientEntryUrl: string, devKey: string): string {
  return [
    `const hooks = globalThis[Symbol.for("graft.dev")].get(${JSON.stringify(devKey)});`,
    `export const dev = true;`,
    `export const clientEntry = ${JSON.stringify(clientEntryUrl)};`,
    `export function getRouteAssets(ids) { return hooks.getRouteAssets(ids); }`,
    "",
  ].join("\n");
}

/** The parts of Vite's build manifest (`.vite/manifest.json`) that Graft reads. */
export type Manifest = Record<
  string,
  { file: string; src?: string; isEntry?: boolean; imports?: string[]; css?: string[] }
>;

/**
 * Source for `virtual:graft/assets` in a production build. The client build
 * has already run, so its manifest says which hashed files each route file
 * became, and the answers are baked into the server bundle.
 */
export function generateBuildAssetsModule(
  manifest: Manifest,
  files: RouteFile[],
  clientEntryKey: string,
  base: string,
): string {
  const url = (file: string): string => `${base.replace(/\/$/, "")}/${file}`;

  /** The chunk's own file and CSS, plus those of every chunk it statically imports. */
  const collect = (key: string): { stylesheets: string[]; modules: string[] } => {
    const stylesheets = new Set<string>();
    const modules = new Set<string>();
    const seen = new Set<string>();

    const visit = (current: string): void => {
      const chunk = manifest[current];
      if (!chunk || seen.has(current)) return;

      seen.add(current);
      modules.add(url(chunk.file));
      chunk.css?.forEach((file) => stylesheets.add(url(file)));
      chunk.imports?.forEach(visit);
    };

    visit(key);

    return { stylesheets: [...stylesheets], modules: [...modules] };
  };

  const entry = manifest[clientEntryKey];
  if (!entry) throw new Error(`Graft couldn't find the client entry in the build manifest.`);

  const routes: Record<string, { stylesheets: string[]; modules: string[] }> = {};
  for (const { id, file } of files) {
    const key = `app/${file}`;
    if (manifest[key]) routes[id] = collect(key);
  }

  // The entry itself is loaded by <script type="module">, so only its imports need preloading.
  const shared = collect(clientEntryKey);
  shared.modules = shared.modules.filter((module) => module !== url(entry.file));

  return `const shared = ${JSON.stringify(shared)};
const routes = ${JSON.stringify(routes)};

export const dev = false;
export const clientEntry = ${JSON.stringify(url(entry.file))};

export async function getRouteAssets(ids) {
  const stylesheets = new Set(shared.stylesheets);
  const modules = new Set(shared.modules);
  for (const id of ids) {
    routes[id]?.stylesheets.forEach((href) => stylesheets.add(href));
    routes[id]?.modules.forEach((href) => modules.add(href));
  }
  return { stylesheets: [...stylesheets], modules: [...modules], precedence: "default" };
}
`;
}
