import { randomUUID } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { createRequest, sendResponse } from "@phatjng/graft-node";
import type { RouteAssets } from "@phatjng/graft-router";
import react from "@vitejs/plugin-react";
import {
  isCSSRequest,
  isRunnableDevEnvironment,
  normalizePath,
  resolveConfig,
  type EnvironmentModuleNode,
  type Logger,
  type Plugin,
  type ResolvedConfig,
  type ViteDevServer,
} from "vite";

import {
  generateBuildAssetsModule,
  generateClientEntry,
  generateDevAssetsModule,
  generateRoutesModule,
  generateRouteTypes,
  generateServerEntry,
  type Manifest,
} from "./codegen";
import { findEntryFile, scanAppDir, type ScanResult } from "./scan";
import { stripServerExports } from "./strip";
import { addTypesInclude, TYPES_INCLUDE } from "./tsconfig";

/**
 * Options for the Graft Vite plugin.
 */
export interface GraftOptions {
  /**
   * Turns the build into what a host expects, for example `vercel()` from
   * `@phatjng/graft/vercel`. Without one, `vite build` writes `dist/` for `graft start`.
   */
  adapter?: GraftAdapter;
}

/**
 * Prepares a build for a host. Hosts like Vercel run a function file rather
 * than a server, and don't install `node_modules` for it, so an adapter wraps
 * the app in the host's function signature and the server build bundles every
 * npm dependency.
 */
export interface GraftAdapter {
  /** Names the adapter's server entry: `dist/server/<name>.js`. */
  name: string;
  /**
   * A module built as an extra server entry next to `dist/server/index.js`. It
   * gets the app's `{ fetch }` by importing `virtual:graft/server`.
   */
  entry: string;
  /** Runs after `vite build` has written the client and the server. */
  adapt(build: GraftBuild): void | Promise<void>;
}

/** What an adapter gets once the build has finished. */
export interface GraftBuild {
  /** Vite's root: the app's folder. */
  root: string;
  /** The browser files, like `dist/client`. Includes `.vite/manifest.json`, which must never be served. */
  clientDir: string;
  /** The server build, like `dist/server`, including the adapter's entry. */
  serverDir: string;
  /** The URL path the app is served under: `/`, or Vite's `base` like `/app/`. */
  basePath: string;
  logger: Logger;
}

// Virtual modules: generated by this plugin rather than read from disk.
const ROUTES_ID = "virtual:graft/routes";
const SERVER_ID = "virtual:graft/server";
const CLIENT_ID = "virtual:graft/client";
const ASSETS_ID = "virtual:graft/assets";
const VIRTUAL_IDS = new Set([ROUTES_ID, SERVER_ID, CLIENT_ID, ASSETS_ID]);

// The "\0" prefix tells other plugins these modules don't exist on disk, so they leave them alone.
const resolved = (id: string): string => `\0${id}`;

// Graft's runtime imports the virtual modules above, so Vite has to process
// it as source instead of handing it to Node or pre-bundling it.
const RUNTIME_PACKAGES = ["@phatjng/graft", "@phatjng/graft-router", "@phatjng/graft-server"];

interface AppState {
  scan: ScanResult;
  serverEntry: string | undefined;
  clientEntry: string | undefined;
}

type ScanState = { ok: true; app: AppState } | { ok: false; error: Error };

interface DevHooks {
  getRouteAssets(ids: string[]): Promise<RouteAssets>;
}

// Lets the dev-only `virtual:graft/assets` reach this plugin (see generateDevAssetsModule).
const DEV_HOOKS = Symbol.for("graft.dev");
const devRegistry = ((globalThis as Record<symbol, unknown>)[DEV_HOOKS] ??= new Map()) as Map<
  string,
  DevHooks
>;

/**
 * The Graft Vite plugin. Add it to `plugins` in `vite.config.ts`.
 *
 * It includes `@vitejs/plugin-react` (JSX and Fast Refresh), so don't add that separately.
 */
export function graft(options: GraftOptions = {}): Plugin[] {
  const main = graftPlugin(options);
  return [serverCodePlugin(main), ...react(), main];
}

/**
 * Writes an app's route types to `.graft/types`, as `vite dev` and `vite build`
 * do, so it can be type-checked without running Vite first. Backs `graft typegen`.
 *
 * Loads the app's Vite config, which runs the `graft()` plugin: the types come
 * from the same code, and respect the config's `root`. Resolves with the path
 * of the file it wrote, or rejects with why `app/` is invalid.
 */
export async function typegen(root: string): Promise<string> {
  const config = await resolveConfig({ root }, "serve");
  const plugin = config.plugins.find((plugin) => plugin.name === "graft") as
    | (Plugin & { api: GraftApi })
    | undefined;

  if (!plugin) {
    throw new Error(
      `The Vite config in ${config.root} doesn't use graft(). Add it to "plugins" in vite.config.ts.`,
    );
  }

  return plugin.api.typegen();
}

/** Matches `db.server.ts`, `secrets.server.js` and so on. */
const SERVER_ONLY_FILE = /\.server\.[cm]?[jt]sx?$/;

/**
 * Keeps server code out of the browser. Runs before other plugins, so it
 * sees each file's original source.
 *
 * - Removes `loader` and `action` from route files, with the code only they use.
 * - Fails when browser code imports a `*.server.*` module. Stripping can't
 *   remove an import that browser code still uses, so this is the backstop.
 */
function serverCodePlugin(main: Plugin & { api: GraftApi }): Plugin {
  return {
    name: "graft:server-code",
    enforce: "pre",

    applyToEnvironment: (environment) => environment.config.consumer === "client",

    async resolveId(source, importer, options) {
      if (!importer || !source.includes(".server")) return;

      const resolvedId = await this.resolve(source, importer, { ...options, skipSelf: true });
      if (resolvedId && SERVER_ONLY_FILE.test(resolvedId.id.split("?")[0]!)) {
        // Vite's dependency scanner reads route files before loaders are
        // stripped. Don't let it follow server-only imports (it would pre-bundle
        // their dependencies for the browser), and don't fail: this import may
        // well be used only by a loader.
        // `scan` is set by Vite during the scan but missing from the hook's types.
        if ((options as { scan?: boolean }).scan) return { id: resolvedId.id, external: true };

        const relative = (id: string): string =>
          path.relative(this.environment.config.root, id.split("?")[0]!);

        this.error(
          `${relative(importer)} imports ${relative(resolvedId.id)}, which is server-only, into code that runs in the browser. ` +
            `Only use it from a loader or action, or from other server-only files.`,
        );
      }

      return resolvedId;
    },

    transform(code, id) {
      if (!main.api.isRouteFile(id.split("?")[0]!)) return;
      return stripServerExports(code, id.split("?")[0]!);
    },
  };
}

interface GraftApi {
  isRouteFile(file: string): boolean;
  /** For `graft typegen`: returns the route types file, or throws why `app/` is invalid. */
  typegen(): string;
}

function graftPlugin({ adapter }: GraftOptions): Plugin & { api: GraftApi } {
  let config: ResolvedConfig;
  let appDir = "";
  let logger: Logger;
  let state: ScanState;
  let signature = "";
  const devKey = randomUUID();

  /**
   * Rescans `app/`. Returns whether anything the virtual modules depend on changed.
   * An invalid app doesn't throw: the error is kept in `state` for the virtual modules to throw.
   */
  function rescan(): boolean {
    try {
      const scan = scanAppDir(appDir);
      const app: AppState = {
        scan,
        serverEntry: findEntryFile(appDir, "server"),
        clientEntry: findEntryFile(appDir, "client"),
      };
      state = { ok: true, app };

      const next = JSON.stringify(app);
      if (next === signature) return false;
      signature = next;
      writeTypes(scan);
      return true;
    } catch (error) {
      state = { ok: false, error: error as Error };
      signature = "";
      return true;
    }
  }

  function logScanError(): void {
    if (!state.ok) logger.error(`[graft] ${state.error.message}`);
  }

  function appState(): AppState {
    if (!state.ok) throw state.error;
    return state.app;
  }

  function typesFile(): string {
    return path.join(config.root, ".graft", "types", "routes.d.ts");
  }

  function writeTypes(scan: ScanResult): void {
    const file = typesFile();
    const dir = path.dirname(file);
    const appImportPath = normalizePath(path.relative(dir, appDir));
    const types = generateRouteTypes(scan.tree, scan.files, appImportPath);

    if (readText(file) === types) return;

    mkdirSync(dir, { recursive: true });
    writeFileSync(file, types);
  }

  function updateTsconfig(): void {
    const file = path.join(config.root, "tsconfig.json");
    const text = readText(file);
    if (text === undefined) return;

    const result = addTypesInclude(text);
    if (result.status === "updated") {
      writeFileSync(file, result.text);
      logger.info(
        `[graft] Added "${TYPES_INCLUDE}" to tsconfig.json so route types are picked up.`,
      );
    } else if (result.status === "unparseable") {
      logger.warn(
        `[graft] Couldn't update tsconfig.json. Add "${TYPES_INCLUDE}" to its "include" so route types are picked up.`,
      );
    }
  }

  /** A URL the browser can request, with Vite's `base` in front. */
  function url(pathname: string): string {
    return `${config.base.replace(/\/$/, "")}${pathname}`;
  }

  /**
   * The CSS and route modules a page needs, read from the server's module
   * graph. The route files have already been imported for rendering, so the
   * graph knows everything they import.
   */
  function createDevHooks(server: ViteDevServer): DevHooks {
    return {
      async getRouteAssets(ids) {
        const graph = server.environments.ssr.moduleGraph;
        const files = new Map(
          appState().scan.files.map((file) => [file.id, `${appDir}/${file.file}`]),
        );
        const stylesheets = new Set<string>();
        const modules: string[] = [];
        const seen = new Set<EnvironmentModuleNode>();

        const visit = (node: EnvironmentModuleNode): void => {
          const mod = followBaseEdge(node);
          if (!mod || seen.has(mod)) return;

          seen.add(mod);
          // Skip `?inline`, `?url` and similar imports, which don't add a stylesheet.
          if (mod.id && isCSSRequest(mod.id) && !mod.id.includes("?"))
            stylesheets.add(url(mod.url));

          mod.importedModules.forEach(visit);
        };

        // Works around a Vite bug: on the server, Vite strips `base` from
        // import URLs it never added it to. With base "/app/", the edge to
        // app/styles.css (URL /app/styles.css) points at an unresolved
        // module /styles.css. Such a node's id is its URL; put the base back.
        const followBaseEdge = (mod: EnvironmentModuleNode): EnvironmentModuleNode | undefined => {
          if (config.base === "/" || mod.id !== mod.url || !mod.url.startsWith("/")) return mod;

          const file = normalizePath(path.join(config.root, config.base, mod.url));
          return [...(graph.getModulesByFile(file) ?? [])][0];
        };

        for (const id of ids) {
          const file = files.get(id);
          const mod = file ? [...(graph.getModulesByFile(file) ?? [])][0] : undefined;
          if (!mod) continue;

          modules.push(url(mod.url));
          visit(mod);
        }

        // hydrate() removes this precedence group once Vite has loaded the same CSS.
        return { stylesheets: [...stylesheets], modules, precedence: "graft-dev" };
      },
    };
  }

  function readClientManifest(): Manifest {
    const client = config.environments.client!.build;
    const file = path.resolve(config.root, client.outDir, ".vite/manifest.json");
    const text = readText(file);
    if (text === undefined) {
      throw new Error(
        `Graft couldn't read the client build manifest at ${file}. Build the client environment first.`,
      );
    }

    return JSON.parse(text) as Manifest;
  }

  /** Tells every environment the virtual modules are stale, and reloads the browser. */
  function reload(server: ViteDevServer): void {
    for (const environment of Object.values(server.environments)) {
      for (const id of VIRTUAL_IDS) {
        const mod = environment.moduleGraph.getModuleById(resolved(id));
        if (mod) environment.moduleGraph.invalidateModule(mod);
      }
    }

    server.environments.client.hot.send({ type: "full-reload" });
  }

  return {
    name: "graft",

    api: {
      typegen() {
        // configResolved has already scanned app/ and written the types.
        if (!state.ok) throw state.error;
        return typesFile();
      },

      isRouteFile(file) {
        if (!state?.ok || !file.startsWith(`${appDir}/`)) return false;

        const relative = file.slice(appDir.length + 1);
        return state.app.scan.files.some((route) => route.file === relative);
      },
    },

    config(userConfig, { command }) {
      // `vite build` writes the browser files to dist/client and the server
      // bundle to dist/server, which `graft start` serves.
      const outDir = userConfig.build?.outDir ?? "dist";

      return {
        // Build every environment with `vite build`, in the order set by buildApp below.
        builder: {},
        environments: {
          client: {
            build: {
              outDir: `${outDir}/client`,
              // Lists which hashed files each source file became. The server build reads it.
              manifest: true,
              rolldownOptions: { input: CLIENT_ID },
            },
          },
          ssr: {
            build: {
              outDir: `${outDir}/server`,
              copyPublicDir: false,
              rolldownOptions: {
                input: { index: SERVER_ID, ...(adapter && { [adapter.name]: adapter.entry }) },
                output: { entryFileNames: "[name].js" },
              },
            },
          },
        },
        // Graft serves HTML itself, so Vite shouldn't look for an index.html.
        appType: "custom",
        // Graft writes generated files here; changes to them shouldn't trigger reloads.
        server: { watch: { ignored: ["**/.graft/**"] } },
        // An adapter's host doesn't install node_modules, so its build bundles
        // everything. Not in dev: Vite's dev server can't run CommonJS packages
        // like React as source.
        ssr: { noExternal: adapter && command === "build" ? true : RUNTIME_PACKAGES },
        optimizeDeps: {
          // With no index.html to crawl, point the dependency scanner at the app instead.
          entries: ["app/**/*.{tsx,ts,jsx,js}", "!app/server.*", "!app/**/*.server.*"],
          exclude: RUNTIME_PACKAGES,
          // Imported by Graft's runtime, which the scanner skips because it's excluded above.
          include: [
            "react",
            "react/jsx-runtime",
            "react/jsx-dev-runtime",
            "react-dom",
            "react-dom/client",
          ],
        },
      };
    },

    async buildApp(builder) {
      // The client goes first: the server bundle needs its manifest.
      await builder.build(builder.environments.client!);
      await builder.build(builder.environments.ssr!);

      if (!adapter) return;

      const outDir = (name: string): string =>
        path.resolve(config.root, config.environments[name]!.build.outDir);

      await adapter.adapt({
        root: config.root,
        clientDir: outDir("client"),
        serverDir: outDir("ssr"),
        // A full-URL base (assets on a CDN) still mounts the app at its path.
        basePath: new URL(config.base, "http://localhost").pathname,
        logger,
      });
    },

    configResolved(resolvedConfig) {
      config = resolvedConfig;

      // Every page's HTML links the same asset URLs, which a relative base
      // would resolve differently on /blog and /blog/hello.
      if (config.command === "build" && config.base.startsWith(".")) {
        throw new Error(
          `Graft apps can't use a relative base ("${config.base}"). Use a path like "/app/" or a full URL.`,
        );
      }

      appDir = normalizePath(path.join(config.root, "app"));
      logger = config.logger;
      rescan();
      updateTsconfig();
    },

    configureServer(server) {
      logScanError();
      devRegistry.set(devKey, createDevHooks(server));
      server.httpServer?.once("close", () => devRegistry.delete(devKey));

      // Adding or removing files can change the routes or entries. Editing a
      // file doesn't, and Vite's HMR already handles edits.
      const onChange = (file: string): void => {
        if (!normalizePath(file).startsWith(`${appDir}/`)) return;
        if (!rescan()) return;

        logScanError();
        reload(server);
      };

      for (const event of ["add", "unlink", "addDir", "unlinkDir"] as const) {
        server.watcher.on(event, onChange);
      }

      // Returning a function adds this middleware after Vite's own, so Vite
      // serves modules and public files first and every other request is a page.
      return () => {
        server.middlewares.use(async (req, res, next) => {
          try {
            const environment = server.environments.ssr;
            if (!isRunnableDevEnvironment(environment)) {
              throw new Error(
                "Graft's dev server needs the ssr environment to run in the Vite process.",
              );
            }

            const entry = await environment.runner.import<{ default?: { fetch?: unknown } }>(
              SERVER_ID,
            );
            const handler = entry.default;
            if (typeof handler?.fetch !== "function") {
              throw new Error(
                "app/server.ts must default-export an object with a fetch(request) method.",
              );
            }

            // With a `base`, Vite strips it from req.url before this middleware.
            // Put it back: the app gets the URL the browser asked for, like in production.
            req.url = (req as { originalUrl?: string }).originalUrl ?? req.url;

            const response: unknown = await handler.fetch(createRequest(req, res));
            if (!(response instanceof Response)) {
              throw new Error("app/server.ts: fetch(request) must return a Response.");
            }

            await sendResponse(res, response);
          } catch (error) {
            if (res.headersSent) return logger.error(`[graft] ${(error as Error).stack ?? error}`);

            // A data request comes from the router, not a page load, so Vite's
            // error page would never be seen. Show Vite's overlay on the open page instead.
            if (new URL(req.url ?? "/", "http://localhost").searchParams.has("_graft_data")) {
              const { message, stack = "" } = error as Error;
              logger.error(`[graft] ${stack || message}`);
              server.environments.client.hot.send({ type: "error", err: { message, stack } });
              res.statusCode = 500;
              return res.end();
            }

            // Vite's error page shows the error in the browser.
            next(error);
          }
        });
      };
    },

    configurePreviewServer(server) {
      // `vite preview` only serves static files, and a Graft app is rendered by
      // its server bundle. Point to `graft start` instead of a 404 for every page.
      const message =
        "Graft apps are previewed with `graft start`, which serves the build with its server. " +
        "Run `vite build`, then `graft start`.";

      server.config.logger.warn(`[graft] ${message}`);

      server.middlewares.use((_req, res) => {
        res.statusCode = 501;
        res.setHeader("content-type", "text/plain; charset=utf-8");
        res.end(`${message}\n`);
      });
    },

    resolveId(id) {
      if (VIRTUAL_IDS.has(id)) return resolved(id);
    },

    load(id) {
      if (!id.startsWith("\0virtual:graft/")) return;

      const app = appState();

      switch (id) {
        case resolved(ROUTES_ID):
          return generateRoutesModule(app.scan.tree, app.scan.files, appDir);
        case resolved(SERVER_ID):
          return generateServerEntry(appDir, app.serverEntry, config.base);
        case resolved(CLIENT_ID):
          return generateClientEntry(
            appDir,
            app.clientEntry,
            config.command === "serve" ? { viteClient: url("/@vite/client") } : undefined,
          );
        case resolved(ASSETS_ID):
          if (config.command === "build") {
            const manifest = readClientManifest();
            return generateBuildAssetsModule(
              manifest,
              app.scan.files,
              clientEntryKey(manifest),
              config.base,
            );
          }

          // Vite serves a virtual module at /@id/ with "\0" encoded as __x00__.
          return generateDevAssetsModule(url(`/@id/__x00__${CLIENT_ID}`), devKey);
      }
    },
  };
}

/** The manifest key of `virtual:graft/client`, the client build's only entry. */
function clientEntryKey(manifest: Manifest): string {
  const key = Object.keys(manifest).find(
    (key) => manifest[key]!.isEntry && key.includes(CLIENT_ID),
  );

  if (!key) throw new Error("Graft couldn't find the client entry in the build manifest.");
  return key;
}

function readText(file: string): string | undefined {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return undefined;
  }
}
