// Modules generated by the Graft Vite plugin (packages/vite). They only exist
// inside a Vite build or dev server, so they stay external when this package is built.

declare module "virtual:graft/routes" {
  import type { RouteNode } from "@phatjng/graft-router";

  export const routes: RouteNode;
  export const modules: Record<string, () => Promise<Record<string, unknown>>>;
}

declare module "virtual:graft/assets" {
  import type { RouteAssets } from "@phatjng/graft-router";

  /** Whether this is Vite's dev server, as opposed to a production build. */
  export const dev: boolean;
  /** URL of the browser entry, loaded with <script type="module">. */
  export const clientEntry: string;
  /** The CSS and JS a set of route files needs. Only call it after importing them. */
  export function getRouteAssets(ids: string[]): Promise<RouteAssets>;
}
