// Modules generated by the Graft Vite plugin (packages/vite). They only exist
// inside a Vite build or dev server, so they stay external when this package is built.

declare module "virtual:graft/routes" {
  import type { RouteNode } from "@phatjng/graft-router";

  export const routes: RouteNode;
  export const modules: Record<string, () => Promise<Record<string, unknown>>>;
}

// Vite replaces `import.meta.env.BASE_URL` when it processes this package
// (see base.ts). Declared here instead of loading all of `vite/client`.
interface ImportMetaEnv {
  readonly BASE_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
